2025-02-28 13:26:38,587 INFO    MainThread:1469040 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7.dev1
2025-02-28 13:26:38,587 INFO    MainThread:1469040 [wandb_setup.py:_flush():67] Configure stats pid to 1469040
2025-02-28 13:26:38,587 INFO    MainThread:1469040 [wandb_setup.py:_flush():67] Loading settings from /data/class/cs175/iklimov/.config/wandb/settings
2025-02-28 13:26:38,587 INFO    MainThread:1469040 [wandb_setup.py:_flush():67] Loading settings from /data/class/cs175/iklimov/PerfectTransitions/scripts/wandb/settings
2025-02-28 13:26:38,587 INFO    MainThread:1469040 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 13:26:38,587 INFO    MainThread:1469040 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /data/class/cs175/iklimov/PerfectTransitions/scripts/wandb/run-20250228_132638-2489tbp4/logs/debug.log
2025-02-28 13:26:38,588 INFO    MainThread:1469040 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /data/class/cs175/iklimov/PerfectTransitions/scripts/wandb/run-20250228_132638-2489tbp4/logs/debug-internal.log
2025-02-28 13:26:38,588 INFO    MainThread:1469040 [wandb_init.py:init():761] calling init triggers
2025-02-28 13:26:38,588 INFO    MainThread:1469040 [wandb_init.py:init():766] wandb.init called with sweep_config: {'batch_size': 64, 'checkpoint_dir': '/./../model_checkpoints', 'embeddings_dir': './../data/embeddings', 'frames': 685, 'hidden_dim': 256, 'lr': 0.000265996416309048, 'lstm_layers': 1, 'margin': 0.2, 'max_epochs': 50, 'patience': 10, 'resume_if_checkpoint_exists': False}
config: {'embeddings_dir': './../data/embeddings', 'checkpoint_dir': '/./../model_checkpoints', 'resume_if_checkpoint_exists': True, 'batch_size': 64, 'num_frames': 685, 'hidden_dim': 256, 'lr': 0.000265996416309048, 'lstm_layers': 1, 'margin': 0.2, 'max_epochs': 50, 'patience': 10, '_wandb': {}}
2025-02-28 13:26:38,588 INFO    MainThread:1469040 [wandb_init.py:init():784] starting backend
2025-02-28 13:26:38,588 INFO    MainThread:1469040 [wandb_init.py:init():788] sending inform_init request
2025-02-28 13:26:38,631 INFO    MainThread:1469040 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-02-28 13:26:38,631 INFO    MainThread:1469040 [wandb_init.py:init():803] backend started and connected
2025-02-28 13:26:38,632 INFO    MainThread:1469040 [wandb_run.py:_config_callback():1261] config_cb None None {'batch_size': 64, 'checkpoint_dir': '/./../model_checkpoints', 'embeddings_dir': './../data/embeddings', 'frames': 685, 'hidden_dim': 256, 'lr': 0.000265996416309048, 'lstm_layers': 1, 'margin': 0.2, 'max_epochs': 50, 'patience': 10, 'resume_if_checkpoint_exists': False}
2025-02-28 13:26:38,632 INFO    MainThread:1469040 [wandb_init.py:init():896] updated telemetry
2025-02-28 13:26:38,697 INFO    MainThread:1469040 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-02-28 13:26:38,906 INFO    MainThread:1469040 [wandb_init.py:init():995] starting run threads in backend
2025-02-28 13:26:46,983 INFO    MainThread:1469040 [wandb_run.py:_console_start():2377] atexit reg
2025-02-28 13:26:46,983 INFO    MainThread:1469040 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-02-28 13:26:46,983 INFO    MainThread:1469040 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-02-28 13:26:46,984 INFO    MainThread:1469040 [wandb_run.py:_redirect():2317] Redirects installed.
2025-02-28 13:26:47,038 INFO    MainThread:1469040 [wandb_init.py:init():1037] run started, returning control to user process
2025-02-28 18:54:31,119 WARNING MsgRouterThr:1469040 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/data/class/cs175/iklimov/.conda/envs/PT/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/data/class/cs175/iklimov/.conda/envs/PT/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/data/class/cs175/iklimov/.conda/envs/PT/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/class/cs175/iklimov/.conda/envs/PT/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/data/class/cs175/iklimov/.conda/envs/PT/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-02-28 18:54:31,168 INFO    MsgRouterThr:1469040 [mailbox.py:close():115] Closing mailbox, abandoning 2 handles.
