2025-02-24 19:53:26,930 INFO    MainThread:713070 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7.dev1
2025-02-24 19:53:26,930 INFO    MainThread:713070 [wandb_setup.py:_flush():67] Configure stats pid to 713070
2025-02-24 19:53:26,930 INFO    MainThread:713070 [wandb_setup.py:_flush():67] Loading settings from /data/class/cs175/iklimov/.config/wandb/settings
2025-02-24 19:53:26,930 INFO    MainThread:713070 [wandb_setup.py:_flush():67] Loading settings from /data/class/cs175/iklimov/PerfectTransitions/scripts/wandb/settings
2025-02-24 19:53:26,930 INFO    MainThread:713070 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-24 19:53:26,930 INFO    MainThread:713070 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /data/class/cs175/iklimov/PerfectTransitions/scripts/wandb/run-20250224_195326-op4q35dr/logs/debug.log
2025-02-24 19:53:26,930 INFO    MainThread:713070 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /data/class/cs175/iklimov/PerfectTransitions/scripts/wandb/run-20250224_195326-op4q35dr/logs/debug-internal.log
2025-02-24 19:53:26,930 INFO    MainThread:713070 [wandb_init.py:init():761] calling init triggers
2025-02-24 19:53:26,930 INFO    MainThread:713070 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'embeddings_dir': './../data/embeddings', 'checkpoint_dir': './../model_checkpoints/lstm', 'batch_size': 32, 'margin': 0.3, 'lstm_layers': 2, 'hidden_dim': 128, 'lr': 0.001, 'max_epochs': 50, 'patience': 5, 'resume_if_checkpoint_exists': True, '_wandb': {}}
2025-02-24 19:53:26,930 INFO    MainThread:713070 [wandb_init.py:init():784] starting backend
2025-02-24 19:53:26,930 INFO    MainThread:713070 [wandb_init.py:init():788] sending inform_init request
2025-02-24 19:53:26,934 INFO    MainThread:713070 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-02-24 19:53:26,934 INFO    MainThread:713070 [wandb_init.py:init():803] backend started and connected
2025-02-24 19:53:26,935 INFO    MainThread:713070 [wandb_init.py:init():896] updated telemetry
2025-02-24 19:53:26,941 INFO    MainThread:713070 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-02-24 19:53:27,360 INFO    MainThread:713070 [wandb_init.py:init():995] starting run threads in backend
2025-02-24 19:53:27,495 INFO    MainThread:713070 [wandb_run.py:_console_start():2377] atexit reg
2025-02-24 19:53:27,495 INFO    MainThread:713070 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-02-24 19:53:27,495 INFO    MainThread:713070 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-02-24 19:53:27,496 INFO    MainThread:713070 [wandb_run.py:_redirect():2317] Redirects installed.
2025-02-24 19:53:27,499 INFO    MainThread:713070 [wandb_init.py:init():1037] run started, returning control to user process
2025-02-24 19:54:14,255 WARNING MsgRouterThr:713070 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/data/class/cs175/iklimov/.conda/envs/PT/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/data/class/cs175/iklimov/.conda/envs/PT/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/data/class/cs175/iklimov/.conda/envs/PT/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/class/cs175/iklimov/.conda/envs/PT/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/data/class/cs175/iklimov/.conda/envs/PT/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-02-24 19:54:14,258 INFO    MsgRouterThr:713070 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
